users:
  Andrew:
    username: Andrew
    articleIds:
      - 1
    commentIds:
      - 1
  b:
    username: b
    articleIds:
      - 2
    commentIds:
      - 2
articles:
  '1':
    id: 1
    title: Stuff
    url: 'https://www.stuff.co.nz'
    username: Andrew
    commentIds:
      - 1
      - 2
    upvotedBy:
      - Andrew
    downvotedBy: []
    comments:
      - &ref_0
        id: 1
        body: STUFF!!!!!
        articleId: 1
        username: Andrew
        commentIds: []
        upvotedBy:
          - b
        downvotedBy:
          - Andrew
  '2':
    id: 2
    title: obn;ofan
    url: befa
    username: b
    commentIds: []
    upvotedBy: []
    downvotedBy:
      - b
nextArticleId: 3
comments:
  '1': *ref_0
  '2':
    id: 2
    body: gn rs
    articleId: 1
    username: b
    commentIds: []
    upvotedBy: []
    downvotedBy:
      - b
nextCommentId: 3
